######################################################################
#
# File name : tb_sopc.udo
# Created on: Sun Jan 09 16:54:53 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
