######################################################################
#
# File name : tb_sopc_simulate.do
# Created on: Sun Jan 09 16:54:53 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_sopc xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_sopc_wave.do}

view wave
view structure
view signals

do {tb_sopc.udo}

run 1000ns
