######################################################################
#
# File name : tb_sopc_wave.do
# Created on: Sun Jan 09 16:54:53 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
